export const OPEN_PROJECT_DETAIL = 'OPEN_PROJECT_DETAIL';
export const CLOSE_PROJECT_DETAIL = 'CLOSE_PROJECT_DETAIL';
export const ACT_HANDLE_CLICK_MENU_ITEM = 'ACT_HANDLE_CLICK_MENU_ITEM';

//Saga actions
export const SGA_DISPLAY_PROJECT_DETAIL = 'SGA_DISPLAY_PROJECT_DETAIL';
export const SGA_HIDE_PROJECT_DETAIL = 'SGA_HIDE_PROJECT_DETAIL';