export const OPEN_PROJECT_DETAIL = 'OPEN_PROJECT_DETAIL';
export const CLOSE_PROJECT_DETAIL = 'CLOSE_PROJECT_DETAIL';
// export const ACT_SCROLL_TO_PROJECT = 'ACT_SCROLL_TO_PROJECT';

//Saga actions
export const SGA_DISPLAY_PROJECT_DETAIL = 'SGA_DISPLAY_PROJECT_DETAIL';
export const SGA_HIDE_PROJECT_DETAIL = 'SGA_HIDE_PROJECT_DETAIL';